// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "6d137f91-5a0d-4bfd-b8a5-04f50a960c84");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1629994502);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1630047105);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1630047465);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1630047345);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1630047225);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1629994382);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1629993930);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1629994622);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 74217);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1629990271);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2c68f1cf-a384-4258-911e-38abb0e4925d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1630048510062");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1630070110062");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200720193547");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1630047080");
user_pref("browser.slowStartup.averageTime", 13460);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1630047079);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1629993927013");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "8981072715c14baeaf47fb3fc91e1fd9");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1629994542);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200720193547");
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3fce7096-c3a1-42d0-afad-21becff3acee\",\"formautofill@mozilla.org\":\"237d935c-2b65-4a4a-8b22-49ca5c4d3286\",\"screenshots@mozilla.org\":\"918a9adc-cea0-4251-b1d4-babb2ba1b1bb\",\"webcompat-reporter@mozilla.org\":\"c27df3ca-8011-49fb-a89a-a6ed6f333eca\",\"webcompat@mozilla.org\":\"b88e3759-521b-48aa-a295-fb2a8d3d5f23\",\"default-theme@mozilla.org\":\"1789561d-d3ce-4c0a-8eb3-15639c984b91\",\"google@search.mozilla.org\":\"5c64deda-a35e-4116-a604-b6dc11fb9723\",\"amazondotcom@search.mozilla.org\":\"adb37e70-0a54-4764-b21d-77eda1929e92\",\"wikipedia@search.mozilla.org\":\"824c51fa-8919-4a19-8f01-912e5fa51918\",\"bing@search.mozilla.org\":\"1b4cec61-42ac-4aa9-9584-3a619077d3b5\",\"ddg@search.mozilla.org\":\"648fee0e-fd8d-412e-9f59-cac87d58f7bb\"}");
user_pref("idle.lastDailyNotification", 1630047882);
user_pref("media.gmp-manager.buildID", "20200720193547");
user_pref("media.gmp-manager.lastCheck", 1629994024);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1630047883);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1630047119);
user_pref("security.remote_settings.intermediates.checked", 1630047119);
user_pref("security.sandbox.content.tempDirSuffix", "982550c8-5858-49f6-8825-c8d8b5efad10");
user_pref("security.sandbox.plugin.tempDirSuffix", "d47e5332-9b7f-4831-b978-9f8cc1cfdc45");
user_pref("services.blocklist.addons.checked", 1630047119);
user_pref("services.blocklist.gfx.checked", 1630047119);
user_pref("services.blocklist.pinning.checked", 1630047119);
user_pref("services.blocklist.plugins.checked", 1630047119);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1630044281274\"");
user_pref("services.settings.last_update_seconds", 1630047119);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1630047119);
user_pref("services.settings.main.cfr-fxa.last_check", 1630047119);
user_pref("services.settings.main.cfr.last_check", 1630047119);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1630047119);
user_pref("services.settings.main.hijack-blocklists.last_check", 1630047119);
user_pref("services.settings.main.language-dictionaries.last_check", 1630047119);
user_pref("services.settings.main.message-groups.last_check", 1630047119);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1630047119);
user_pref("services.settings.main.pioneer-study-addons.last_check", 1630047119);
user_pref("services.settings.main.public-suffix-list.last_check", 1630047119);
user_pref("services.settings.main.search-config.last_check", 1630047119);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1630047119);
user_pref("services.settings.main.sites-classification.last_check", 1630047119);
user_pref("services.settings.main.tippytop.last_check", 1630047119);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1630047119);
user_pref("services.settings.main.whats-new-panel.last_check", 1630047119);
user_pref("services.settings.security.onecrl.checked", 1630047119);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1630047882);
user_pref("toolkit.startup.last_success", 1630047070);
user_pref("toolkit.telemetry.cachedClientID", "00f15812-ec2b-4997-a9e8-9453703148fb");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
